"""add rnp_items table

Revision ID: 8017d2c76f97
Revises: 0001_initial_schema
Create Date: 2026-09-11 06:05:49.639672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8017d2c76f97'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rnp_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('month_name', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('person', sa.String(), nullable=True),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('prev_fact', sa.String(), nullable=True),
    sa.Column('prev_percent', sa.String(), nullable=True),
    sa.Column('plan_month', sa.String(), nullable=True),
    sa.Column('fact_month', sa.String(), nullable=True),
    sa.Column('percent_month', sa.Float(), nullable=True),
    sa.Column('forecast', sa.String(), nullable=True),
    sa.Column('w1_plan', sa.String(), nullable=True),
    sa.Column('w1_fact', sa.String(), nullable=True),
    sa.Column('w2_plan', sa.String(), nullable=True),
    sa.Column('w2_fact', sa.String(), nullable=True),
    sa.Column('w3_plan', sa.String(), nullable=True),
    sa.Column('w3_fact', sa.String(), nullable=True),
    sa.Column('w4_plan', sa.String(), nullable=True),
    sa.Column('w4_fact', sa.String(), nullable=True),
    sa.Column('w5_plan', sa.String(), nullable=True),
    sa.Column('w5_fact', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rnp_items_id'), 'rnp_items', ['id'], unique=False)
    op.create_index(op.f('ix_rnp_items_month_name'), 'rnp_items', ['month_name'], unique=False)
    op.create_index(op.f('ix_rnp_items_project_name'), 'rnp_items', ['project_name'], unique=False)
    op.create_index(op.f('ix_rnp_items_section'), 'rnp_items', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rnp_items_section'), table_name='rnp_items')
    op.drop_index(op.f('ix_rnp_items_project_name'), table_name='rnp_items')
    op.drop_index(op.f('ix_rnp_items_month_name'), table_name='rnp_items')
    op.drop_index(op.f('ix_rnp_items_id'), table_name='rnp_items')
    op.drop_table('rnp_items')
    # ### end Alembic commands ###

